all: simple_stack_reverse stack_reverse

simple_stack_reverse:
	gcc -o simple_stack_reverse simple_stack_reverse.c
stack_reverse:
	gcc -o stack_reverse stack_reverse.c

clear:
	rm simple_stack_reverse stack_reverse